name: Build Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.6.2 

    - name: Install dependencies
      run: npm install -g esbuild

    - name: Build project
      run: npm run build-es
      env:
        NODE_ENV: production
