name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setting environment...
      uses: actions/setup-node@v2
      with:
        node-version: 21

    - name: Installing dependencies..
      run: npm install -g esbuild

    - name: Building project..
      run: npm run build-es
      env:
        NODE_ENV: production

    - name: bad devs!!!!!
      if: failure()
      run: exit 1
