name: automatic bun build
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

                  
    - name: Setup Bun Runtime         
      uses: antongolub/action-setup-bun@v1.13.1



    - name: Build
      run: |
        npm install
        bun run build-bun
        
    - name: Write changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
