name: BunJS with Webpack
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Bun.js
      uses: oven-sh/setup-bun@v2
      
    - name: Build
      run: |
        bun install -g webpack-cli
        webpack --config webpack.config.js
    - name: Write changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
